language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('punkt');"
  - python -c "import nltk; nltk.download('stopwords');"
  - python -c "import nltk; nltk.download('wordnet')"
script:
  - python -m unittest -v tests/*.py
notifications:
  email: false

